// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHecsa.Data;

namespace WebHecsa.Migrations
{
    [DbContext(typeof(nDbContext))]
    partial class nDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebHecsa.Models.CatArea", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.HasKey("IdArea");

                    b.HasIndex("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa");

                    b.ToTable("CatAreas");
                });

            modelBuilder.Entity("WebHecsa.Models.CatCategoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoriaDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int?>("IdMarcaNavigationIdMarca")
                        .HasColumnType("int");

                    b.Property<int?>("IdMarcaNavigationIdMarcaNavigationIdMarca")
                        .HasColumnType("int");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdMarcaNavigationIdMarcaNavigationIdMarca");

                    b.ToTable("CatCategorias");
                });

            modelBuilder.Entity("WebHecsa.Models.CatCodigosPostale", b =>
                {
                    b.Property<int>("IdCodigosPostales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCodigosPostales")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ccp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcveCiudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cestado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cmnpio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coficina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtipoAsenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dasenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dcodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dcp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dmnpio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtipoAsenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dzona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdAsentaCpcons")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCodigosPostales");

                    b.ToTable("CatCodigosPostales");
                });

            modelBuilder.Entity("WebHecsa.Models.CatDivisa", b =>
                {
                    b.Property<int>("IdDivisa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DivisaDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.HasKey("IdDivisa");

                    b.ToTable("CatDivisas");
                });

            modelBuilder.Entity("WebHecsa.Models.CatEstatus", b =>
                {
                    b.Property<int>("IdEstatusRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstatusDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.HasKey("IdEstatusRegistro");

                    b.ToTable("CatEstatus");
                });

            modelBuilder.Entity("WebHecsa.Models.CatGenero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneroDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.HasKey("IdGenero");

                    b.ToTable("CatGeneros");
                });

            modelBuilder.Entity("WebHecsa.Models.CatMarca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<Guid>("IdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProveedorNavigationIdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProveedorNavigationIdProveedorNavigationIdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MarcaDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMarca");

                    b.HasIndex("IdProveedorNavigationIdProveedorNavigationIdProveedor");

                    b.ToTable("CatMarcas");
                });

            modelBuilder.Entity("WebHecsa.Models.CatPerfile", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("PerfilDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerfil");

                    b.ToTable("CatPerfiles");
                });

            modelBuilder.Entity("WebHecsa.Models.CatProducto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("int");

                    b.Property<string>("CodigoExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdCategoriaNavigationIdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdCategoriaNavigationIdCategoriaNavigationIdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajePrecioUno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductoPrecioUno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubCosto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoriaNavigationIdCategoriaNavigationIdCategoria");

                    b.ToTable("CatProductos");
                });

            modelBuilder.Entity("WebHecsa.Models.CatRole", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("RolDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("CatRoles");
                });

            modelBuilder.Entity("WebHecsa.Models.CatTipoDireccion", b =>
                {
                    b.Property<int>("IdTipoDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("TipoDireccionDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoDireccion");

                    b.ToTable("CatTipoDireccions");
                });

            modelBuilder.Entity("WebHecsa.Models.CatTipoEnvio", b =>
                {
                    b.Property<int>("IdTiposEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("TiposEnvioDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTiposEnvio");

                    b.ToTable("CatTipoEnvios");
                });

            modelBuilder.Entity("WebHecsa.Models.CatTiposEstatus", b =>
                {
                    b.Property<int>("IdTipoEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("TipoEstatusDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoEstatus");

                    b.ToTable("CatTiposEstatus");
                });

            modelBuilder.Entity("WebHecsa.Models.TblCliente", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiroComercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaNavigationIdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rfc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa");

                    b.ToTable("TblClientes");
                });

            modelBuilder.Entity("WebHecsa.Models.TblClienteContacto", b =>
                {
                    b.Property<int>("IdClienteContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdClienteNavigationIdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdClienteNavigationIdClienteNavigationIdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("NombreClienteContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoMovil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClienteContacto");

                    b.HasIndex("IdClienteNavigationIdClienteNavigationIdCliente");

                    b.ToTable("TblClienteContactos");
                });

            modelBuilder.Entity("WebHecsa.Models.TblClienteDireccion", b =>
                {
                    b.Property<int>("IdClienteDirecciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdClienteNavigationIdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdClienteNavigationIdClienteNavigationIdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdColonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDireccion")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDireccionNavigationIdTipoDireccion")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDireccionNavigationIdTipoDireccionNavigationIdTipoDireccion")
                        .HasColumnType("int");

                    b.Property<string>("LocalidadMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClienteDirecciones");

                    b.HasIndex("IdClienteNavigationIdClienteNavigationIdCliente");

                    b.HasIndex("IdTipoDireccionNavigationIdTipoDireccionNavigationIdTipoDireccion");

                    b.ToTable("TblClienteDirecciones");
                });

            modelBuilder.Entity("WebHecsa.Models.TblCotizacionGeneral", b =>
                {
                    b.Property<Guid>("IdCotizacionGeneral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdDivisa")
                        .HasColumnType("int");

                    b.Property<int?>("IdDivisaNavigationIdDivisa")
                        .HasColumnType("int");

                    b.Property<int?>("IdDivisaNavigationIdDivisaNavigationIdDivisa")
                        .HasColumnType("int");

                    b.Property<Guid>("IdEmpresaFiscales")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaFiscalesNavigationIdEmpresaFiscales")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaFiscalesNavigationIdEmpresaFiscalesNavigationIdEmpresaFiscales")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdTiposEnvio")
                        .HasColumnType("int");

                    b.Property<int?>("IdTiposEnvioNavigationIdTiposEnvio")
                        .HasColumnType("int");

                    b.Property<int?>("IdTiposEnvioNavigationIdTiposEnvioNavigationIdTiposEnvio")
                        .HasColumnType("int");

                    b.Property<string>("MediosCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCotizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rfccliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCotizacionGeneral");

                    b.HasIndex("IdDivisaNavigationIdDivisaNavigationIdDivisa");

                    b.HasIndex("IdEmpresaFiscalesNavigationIdEmpresaFiscalesNavigationIdEmpresaFiscales");

                    b.HasIndex("IdTiposEnvioNavigationIdTiposEnvioNavigationIdTiposEnvio");

                    b.ToTable("TblCotizacionGenerals");
                });

            modelBuilder.Entity("WebHecsa.Models.TblEmpresa", b =>
                {
                    b.Property<Guid>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiroComercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdColonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstatusRegistroNavigationIdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstatusRegistroNavigationIdEstatusRegistroNavigationIdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("LocalidadMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rfc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("IdEstatusRegistroNavigationIdEstatusRegistroNavigationIdEstatusRegistro");

                    b.ToTable("TblEmpresas");
                });

            modelBuilder.Entity("WebHecsa.Models.TblEmpresaFiscal", b =>
                {
                    b.Property<Guid>("IdEmpresaFiscales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdColonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaNavigationIdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("LocalidadMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rfc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresaFiscales");

                    b.HasIndex("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa");

                    b.ToTable("TblEmpresaFiscales");
                });

            modelBuilder.Entity("WebHecsa.Models.TblProveedor", b =>
                {
                    b.Property<Guid>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiroComercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaNavigationIdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<string>("NombreProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rfc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProveedor");

                    b.HasIndex("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa");

                    b.ToTable("TblProveedors");
                });

            modelBuilder.Entity("WebHecsa.Models.TblProveedorContacto", b =>
                {
                    b.Property<int>("IdProveedorContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<Guid>("IdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProveedorNavigationIdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProveedorNavigationIdProveedorNavigationIdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreProveedorContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoMovil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProveedorContacto");

                    b.HasIndex("IdProveedorNavigationIdProveedorNavigationIdProveedor");

                    b.ToTable("TblProveedorContactos");
                });

            modelBuilder.Entity("WebHecsa.Models.TblProveedorDireccion", b =>
                {
                    b.Property<int>("IdProveedorDirecciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdColonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<Guid>("IdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProveedorNavigationIdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProveedorNavigationIdProveedorNavigationIdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdTipoDireccion")
                        .HasColumnType("int");

                    b.Property<string>("LocalidadMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProveedorDirecciones");

                    b.HasIndex("IdProveedorNavigationIdProveedorNavigationIdProveedor");

                    b.ToTable("TblProveedorDirecciones");
                });

            modelBuilder.Entity("WebHecsa.Models.TblUsuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoAcceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.Property<int?>("IdAreaNavigationIdArea")
                        .HasColumnType("int");

                    b.Property<int?>("IdAreaNavigationIdAreaNavigationIdArea")
                        .HasColumnType("int");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdEstatusRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<int?>("IdGeneroNavigationIdGenero")
                        .HasColumnType("int");

                    b.Property<int?>("IdGeneroNavigationIdGeneroNavigationIdGenero")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<int?>("IdPerfilNavigationIdPerfil")
                        .HasColumnType("int");

                    b.Property<int?>("IdPerfilNavigationIdPerfilNavigationIdPerfil")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdRolNavigationIdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdRolNavigationIdRolNavigationIdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdAreaNavigationIdAreaNavigationIdArea");

                    b.HasIndex("IdGeneroNavigationIdGeneroNavigationIdGenero");

                    b.HasIndex("IdPerfilNavigationIdPerfilNavigationIdPerfil");

                    b.HasIndex("IdRolNavigationIdRolNavigationIdRol");

                    b.ToTable("TblUsuarios");
                });

            modelBuilder.Entity("WebHecsa.Models.CatArea", b =>
                {
                    b.HasOne("WebHecsa.Models.TblEmpresa", "IdEmpresaNavigationIdEmpresaNavigation")
                        .WithMany("CatAreas")
                        .HasForeignKey("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa");

                    b.Navigation("IdEmpresaNavigationIdEmpresaNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.CatCategoria", b =>
                {
                    b.HasOne("WebHecsa.Models.CatMarca", "IdMarcaNavigationIdMarcaNavigation")
                        .WithMany("CatCategoria")
                        .HasForeignKey("IdMarcaNavigationIdMarcaNavigationIdMarca");

                    b.Navigation("IdMarcaNavigationIdMarcaNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.CatMarca", b =>
                {
                    b.HasOne("WebHecsa.Models.TblProveedor", "IdProveedorNavigationIdProveedorNavigation")
                        .WithMany("CatMarcas")
                        .HasForeignKey("IdProveedorNavigationIdProveedorNavigationIdProveedor");

                    b.Navigation("IdProveedorNavigationIdProveedorNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.CatProducto", b =>
                {
                    b.HasOne("WebHecsa.Models.CatCategoria", "IdCategoriaNavigationIdCategoriaNavigation")
                        .WithMany("CatProductos")
                        .HasForeignKey("IdCategoriaNavigationIdCategoriaNavigationIdCategoria");

                    b.Navigation("IdCategoriaNavigationIdCategoriaNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblCliente", b =>
                {
                    b.HasOne("WebHecsa.Models.TblEmpresa", "IdEmpresaNavigationIdEmpresaNavigation")
                        .WithMany("TblClientes")
                        .HasForeignKey("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa");

                    b.Navigation("IdEmpresaNavigationIdEmpresaNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblClienteContacto", b =>
                {
                    b.HasOne("WebHecsa.Models.TblCliente", "IdClienteNavigationIdClienteNavigation")
                        .WithMany("TblClienteContactos")
                        .HasForeignKey("IdClienteNavigationIdClienteNavigationIdCliente");

                    b.Navigation("IdClienteNavigationIdClienteNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblClienteDireccion", b =>
                {
                    b.HasOne("WebHecsa.Models.TblCliente", "IdClienteNavigationIdClienteNavigation")
                        .WithMany("TblClienteDirecciones")
                        .HasForeignKey("IdClienteNavigationIdClienteNavigationIdCliente");

                    b.HasOne("WebHecsa.Models.CatTipoDireccion", "IdTipoDireccionNavigationIdTipoDireccionNavigation")
                        .WithMany("TblClienteDirecciones")
                        .HasForeignKey("IdTipoDireccionNavigationIdTipoDireccionNavigationIdTipoDireccion");

                    b.Navigation("IdClienteNavigationIdClienteNavigation");

                    b.Navigation("IdTipoDireccionNavigationIdTipoDireccionNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblCotizacionGeneral", b =>
                {
                    b.HasOne("WebHecsa.Models.CatDivisa", "IdDivisaNavigationIdDivisaNavigation")
                        .WithMany("TblCotizacionGenerals")
                        .HasForeignKey("IdDivisaNavigationIdDivisaNavigationIdDivisa");

                    b.HasOne("WebHecsa.Models.TblEmpresaFiscal", "IdEmpresaFiscalesNavigationIdEmpresaFiscalesNavigation")
                        .WithMany("TblCotizacionGenerals")
                        .HasForeignKey("IdEmpresaFiscalesNavigationIdEmpresaFiscalesNavigationIdEmpresaFiscales");

                    b.HasOne("WebHecsa.Models.CatTipoEnvio", "IdTiposEnvioNavigationIdTiposEnvioNavigation")
                        .WithMany("TblCotizacionGenerals")
                        .HasForeignKey("IdTiposEnvioNavigationIdTiposEnvioNavigationIdTiposEnvio");

                    b.Navigation("IdDivisaNavigationIdDivisaNavigation");

                    b.Navigation("IdEmpresaFiscalesNavigationIdEmpresaFiscalesNavigation");

                    b.Navigation("IdTiposEnvioNavigationIdTiposEnvioNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblEmpresa", b =>
                {
                    b.HasOne("WebHecsa.Models.CatEstatus", "IdEstatusRegistroNavigationIdEstatusRegistroNavigation")
                        .WithMany("TblEmpresas")
                        .HasForeignKey("IdEstatusRegistroNavigationIdEstatusRegistroNavigationIdEstatusRegistro");

                    b.Navigation("IdEstatusRegistroNavigationIdEstatusRegistroNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblEmpresaFiscal", b =>
                {
                    b.HasOne("WebHecsa.Models.TblEmpresa", "IdEmpresaNavigationIdEmpresaNavigation")
                        .WithMany("TblEmpresaFiscales")
                        .HasForeignKey("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa");

                    b.Navigation("IdEmpresaNavigationIdEmpresaNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblProveedor", b =>
                {
                    b.HasOne("WebHecsa.Models.TblEmpresa", "IdEmpresaNavigationIdEmpresaNavigation")
                        .WithMany("TblProveedors")
                        .HasForeignKey("IdEmpresaNavigationIdEmpresaNavigationIdEmpresa");

                    b.Navigation("IdEmpresaNavigationIdEmpresaNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblProveedorContacto", b =>
                {
                    b.HasOne("WebHecsa.Models.TblProveedor", "IdProveedorNavigationIdProveedorNavigation")
                        .WithMany("TblProveedorContactos")
                        .HasForeignKey("IdProveedorNavigationIdProveedorNavigationIdProveedor");

                    b.Navigation("IdProveedorNavigationIdProveedorNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblProveedorDireccion", b =>
                {
                    b.HasOne("WebHecsa.Models.TblProveedor", "IdProveedorNavigationIdProveedorNavigation")
                        .WithMany("TblProveedorDirecciones")
                        .HasForeignKey("IdProveedorNavigationIdProveedorNavigationIdProveedor");

                    b.Navigation("IdProveedorNavigationIdProveedorNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.TblUsuario", b =>
                {
                    b.HasOne("WebHecsa.Models.CatArea", "IdAreaNavigationIdAreaNavigation")
                        .WithMany("TblUsuarios")
                        .HasForeignKey("IdAreaNavigationIdAreaNavigationIdArea");

                    b.HasOne("WebHecsa.Models.CatGenero", "IdGeneroNavigationIdGeneroNavigation")
                        .WithMany("TblUsuarios")
                        .HasForeignKey("IdGeneroNavigationIdGeneroNavigationIdGenero");

                    b.HasOne("WebHecsa.Models.CatPerfile", "IdPerfilNavigationIdPerfilNavigation")
                        .WithMany("TblUsuarios")
                        .HasForeignKey("IdPerfilNavigationIdPerfilNavigationIdPerfil");

                    b.HasOne("WebHecsa.Models.CatRole", "IdRolNavigationIdRolNavigation")
                        .WithMany("TblUsuarios")
                        .HasForeignKey("IdRolNavigationIdRolNavigationIdRol");

                    b.Navigation("IdAreaNavigationIdAreaNavigation");

                    b.Navigation("IdGeneroNavigationIdGeneroNavigation");

                    b.Navigation("IdPerfilNavigationIdPerfilNavigation");

                    b.Navigation("IdRolNavigationIdRolNavigation");
                });

            modelBuilder.Entity("WebHecsa.Models.CatArea", b =>
                {
                    b.Navigation("TblUsuarios");
                });

            modelBuilder.Entity("WebHecsa.Models.CatCategoria", b =>
                {
                    b.Navigation("CatProductos");
                });

            modelBuilder.Entity("WebHecsa.Models.CatDivisa", b =>
                {
                    b.Navigation("TblCotizacionGenerals");
                });

            modelBuilder.Entity("WebHecsa.Models.CatEstatus", b =>
                {
                    b.Navigation("TblEmpresas");
                });

            modelBuilder.Entity("WebHecsa.Models.CatGenero", b =>
                {
                    b.Navigation("TblUsuarios");
                });

            modelBuilder.Entity("WebHecsa.Models.CatMarca", b =>
                {
                    b.Navigation("CatCategoria");
                });

            modelBuilder.Entity("WebHecsa.Models.CatPerfile", b =>
                {
                    b.Navigation("TblUsuarios");
                });

            modelBuilder.Entity("WebHecsa.Models.CatRole", b =>
                {
                    b.Navigation("TblUsuarios");
                });

            modelBuilder.Entity("WebHecsa.Models.CatTipoDireccion", b =>
                {
                    b.Navigation("TblClienteDirecciones");
                });

            modelBuilder.Entity("WebHecsa.Models.CatTipoEnvio", b =>
                {
                    b.Navigation("TblCotizacionGenerals");
                });

            modelBuilder.Entity("WebHecsa.Models.TblCliente", b =>
                {
                    b.Navigation("TblClienteContactos");

                    b.Navigation("TblClienteDirecciones");
                });

            modelBuilder.Entity("WebHecsa.Models.TblEmpresa", b =>
                {
                    b.Navigation("CatAreas");

                    b.Navigation("TblClientes");

                    b.Navigation("TblEmpresaFiscales");

                    b.Navigation("TblProveedors");
                });

            modelBuilder.Entity("WebHecsa.Models.TblEmpresaFiscal", b =>
                {
                    b.Navigation("TblCotizacionGenerals");
                });

            modelBuilder.Entity("WebHecsa.Models.TblProveedor", b =>
                {
                    b.Navigation("CatMarcas");

                    b.Navigation("TblProveedorContactos");

                    b.Navigation("TblProveedorDirecciones");
                });
#pragma warning restore 612, 618
        }
    }
}
